import type { AdapterConfig } from "@/db/schema";

export type CatalogCompany = {
  name: string;
  slug: string;
  adapterKey: string;
  adapterConfig?: AdapterConfig;
  careersUrl: string;
  enabled?: boolean;
};

function gh(
  name: string,
  slug: string,
  board: string,
  careersUrl?: string,
): CatalogCompany {
  return {
    name,
    slug,
    adapterKey: "greenhouse",
    adapterConfig: { board },
    careersUrl: careersUrl ?? `https://job-boards.greenhouse.io/${board}`,
    enabled: true,
  };
}

function lever(name: string, slug: string, board: string): CatalogCompany {
  return {
    name,
    slug,
    adapterKey: "lever",
    adapterConfig: { board },
    careersUrl: `https://jobs.lever.co/${board}`,
    enabled: true,
  };
}

function ashby(name: string, slug: string, board: string): CatalogCompany {
  return {
    name,
    slug,
    adapterKey: "ashby",
    adapterConfig: { board },
    careersUrl: `https://jobs.ashbyhq.com/${board}`,
    enabled: true,
  };
}

function workday(
  name: string,
  slug: string,
  tenant: string,
  site: string,
  wdInstance = "wd5",
): CatalogCompany {
  return {
    name,
    slug,
    adapterKey: "workday",
    adapterConfig: { tenant, site, wdInstance },
    careersUrl: `https://${tenant}.${wdInstance}.myworkdayjobs.com/${site}`,
    enabled: true,
  };
}

function manual(name: string, slug: string, careersUrl: string): CatalogCompany {
  return {
    name,
    slug,
    adapterKey: "manual",
    careersUrl,
    enabled: false,
  };
}

/** Original FAANG/MAANG custom adapters */
export const LEGACY_COMPANIES: CatalogCompany[] = [
  {
    name: "Google",
    slug: "google",
    adapterKey: "google",
    careersUrl: "https://careers.google.com/jobs/results/",
  },
  {
    name: "Meta",
    slug: "meta",
    adapterKey: "meta",
    careersUrl: "https://www.metacareers.com/jobs",
  },
  {
    name: "Amazon",
    slug: "amazon",
    adapterKey: "amazon",
    careersUrl: "https://www.amazon.jobs/en/search",
  },
  {
    name: "Apple",
    slug: "apple",
    adapterKey: "apple",
    careersUrl: "https://jobs.apple.com/en-us/search",
  },
  {
    name: "Microsoft",
    slug: "microsoft",
    adapterKey: "microsoft",
    careersUrl: "https://careers.microsoft.com/us/en/search-results",
  },
  {
    name: "Netflix",
    slug: "netflix",
    adapterKey: "netflix",
    careersUrl: "https://explore.jobs.netflix.net/careers",
  },
];

export const GREENHOUSE_COMPANIES: CatalogCompany[] = [
  gh("Databricks", "databricks", "databricks"),
  gh("Datadog", "datadog", "datadog"),
  gh("Brex", "brex", "brex"),
  gh("MongoDB", "mongodb", "mongodb"),
  gh("Robinhood", "robinhood", "robinhood"),
  gh("Anduril", "anduril", "andurilindustries"),
  gh("Stripe", "stripe", "stripe"),
  gh("CoreWeave", "coreweave", "coreweave"),
  gh("Pure Storage", "pure-storage", "purestorage"),
  gh("Wiz", "wiz", "wizinc"),
  gh("Glean", "glean", "gleanwork"),
  gh("Waymo", "waymo", "waymo"),
  gh("Airbnb", "airbnb", "airbnb"),
  gh("Dropbox", "dropbox", "dropbox"),
  gh("Coinbase", "coinbase", "coinbase"),
  gh("Instacart", "instacart", "instacart"),
  gh("Toast", "toast", "toast"),
  gh("Okta", "okta", "okta"),
  gh("LinkedIn", "linkedin", "linkedin"),
  gh("Figma", "figma", "figma"),
  gh("Asana", "asana", "asana"),
  gh("Pinterest", "pinterest", "pinterest"),
  gh("Lyft", "lyft", "lyft"),
  gh("Airtable", "airtable", "airtable"),
  gh("Vercel", "vercel", "vercel"),
  gh("Nuro", "nuro", "nuro"),
  gh("Databento", "databento", "databento"),
  gh("Warp", "warp", "warp"),
  gh("Attentive", "attentive", "attentive"),
  gh("Gusto", "gusto", "gusto"),
  gh("Roblox", "roblox", "roblox"),
  gh("Kalshi", "kalshi", "kalshi"),
  gh("Gemini Exchange", "gemini-exchange", "gemini"),
  gh("Chainguard", "chainguard", "chainguard"),
  gh("Underdog Sports", "underdog-sports", "underdogfantasy"),
  gh("Fireworks AI", "fireworks-ai", "fireworksai"),
  gh("Vast Space", "vast-space", "vast"),
  gh("Oklo", "oklo", "oklo"),
  gh("Five Rings", "five-rings", "fiveringsllc"),
  gh("IMC", "imc", "imc"),
  gh("Akuna Capital", "akuna-capital", "akunacapital"),
  gh("Jump Trading", "jump-trading", "jumptrading"),
  gh("Point72", "point72", "point72"),
  gh("Virtu Financial", "virtu-financial", "virtu"),
  gh("Old Mission Capital", "old-mission-capital", "oldmissioncapital"),
  gh("Jane Street", "jane-street", "janestreet"),
  gh("Riot Games", "riot-games", "riotgames"),
  gh("Twitch", "twitch", "twitch"),
  gh("Discord", "discord", "discord"),
  gh("Scale AI", "scale-ai", "scaleai"),
  gh("Together AI", "together-ai", "togetherai"),
  gh("Thinking Machines Lab", "thinking-machines-lab", "thinkingmachines"),
  gh("The Nuclear Company", "the-nuclear-company", "thenuclearcompany"),
  gh("Anthropic", "anthropic", "anthropic"),
  gh("Chime", "chime", "chime"),
  gh("Sofi", "sofi", "sofi"),
  // Round 2: LinkedIn following list
  gh("Affirm", "affirm", "affirm"),
  gh("SeatGeek", "seatgeek", "seatgeek"),
  gh("Google DeepMind", "google-deepmind", "deepmind"),
  gh("Pindrop", "pindrop", "pindropsecurity"),
  gh("Engine", "engine", "engine"),
  gh("PathAI", "pathai", "pathai"),
  gh("Parallel Web Systems", "parallel-web-systems", "parallel"),
  gh("Smartsheet", "smartsheet", "smartsheet"),
  gh("Cloudflare", "cloudflare", "cloudflare"),
  gh("Figure", "figure", "figureai"),
  gh("Reflex", "reflex", "reflex"),
  gh("Hightouch", "hightouch", "hightouch"),
  gh("Actively AI", "actively-ai", "activelyai"),
  gh("LPL Financial", "lpl-financial", "lpl"),
  gh("Yugabyte", "yugabyte", "yugabyte"),
  gh("SingleStore", "singlestore", "singlestore"),
  gh("Cockroach Labs", "cockroach-labs", "cockroachlabs"),
  gh("PlanetScale", "planetscale", "planetscale"),
  gh("Twilio", "twilio", "twilio"),
];

export const LEVER_COMPANIES: CatalogCompany[] = [
  lever("Palantir", "palantir", "palantir"),
  lever("Belvedere Trading", "belvedere-trading", "belvederetrading"),
  lever("Spotify", "spotify", "spotify"),
  lever("Crypto.com", "crypto-com", "crypto"),
  lever("Mistral AI", "mistral-ai", "mistral"),
  lever("Rigetti Computing", "rigetti-computing", "rigetti"),
  // Round 2: LinkedIn following list
  lever("Iru", "iru", "iru"),
  lever("Mega", "mega", "mega"),
  lever("Veeva Systems", "veeva-systems", "veeva"),
];

export const ASHBY_COMPANIES: CatalogCompany[] = [
  ashby("Snowflake", "snowflake", "snowflake"),
  ashby("Ramp", "ramp", "ramp"),
  ashby("Plaid", "plaid", "plaid"),
  ashby("Confluent", "confluent", "confluent"),
  ashby("Notion", "notion", "notion"),
  ashby("Saronic Technologies", "saronic-technologies", "saronic"),
  ashby("Perplexity", "perplexity", "perplexity"),
  ashby("OpenAI", "openai", "openai"),
  ashby("Mercor", "mercor", "mercor"),
  ashby("Common Room", "common-room", "commonroom"),
  ashby("Synctera", "synctera", "synctera"),
  ashby("ElevenLabs", "elevenlabs", "elevenlabs"),
  ashby("Harvey AI", "harvey-ai", "harvey"),
  ashby("Polymarket", "polymarket", "polymarket"),
  ashby("UiPath", "uipath", "uipath"),
  ashby("Cursor", "cursor", "cursor"),
  // Round 2: LinkedIn following list
  ashby("Ironclad", "ironclad", "ironcladhq"),
  ashby("Stilta", "stilta", "stilta"),
  ashby("Shapes Inc", "shapes-inc", "shapes"),
  ashby("GridCARE", "gridcare", "gridcare"),
  ashby("Cerebras", "cerebras", "cerebras"),
  ashby("Linear", "linear", "linear"),
  ashby("Supercell", "supercell", "supercell"),
  ashby("Monk", "monk", "monk"),
  ashby("Greptile", "greptile", "greptile"),
  ashby("Dust", "dust", "dust"),
  ashby("Geordie AI", "geordie-ai", "geordieai"),
  ashby("DualEntry", "dualentry", "dualentry"),
  ashby("Traversal", "traversal", "traversal"),
  ashby("Peec AI", "peec-ai", "peec"),
  ashby("Serval", "serval", "serval"),
  ashby("Reducto", "reducto", "reducto"),
  ashby("Rho", "rho", "rho"),
  ashby("Aaru", "aaru", "aaru"),
  ashby("Cohere", "cohere", "cohere"),
  ashby("The Better Money Company", "the-better-money-company", "bettermoney"),
  ashby("Mariana Minerals", "mariana-minerals", "marianaminerals"),
  ashby("Concourse", "concourse", "concourse"),
  ashby("Lio", "lio", "lio"),
  ashby("Braintrust", "braintrust", "braintrust"),
  ashby("Protege", "protege", "protege"),
  ashby("Nexxa.ai", "nexxa-ai", "nexxa"),
  ashby("Sentra", "sentra", "sentra"),
  ashby("Phylo", "phylo", "phylo"),
  ashby("Dex", "dex", "dex"),
  ashby("Vanta", "vanta", "vanta"),
  ashby("Composio", "composio", "composio"),
  ashby("Liquid AI", "liquid-ai", "liquid"),
  ashby("Reflection AI", "reflection-ai", "reflectionai"),
  ashby("Maybern", "maybern", "maybern"),
  ashby("Redis", "redis", "redis"),
  ashby("Y Combinator", "y-combinator", "ycombinator"),
  ashby("Rillet", "rillet", "rillet"),
  ashby("Check", "check", "check-technologies"),
  ashby("Meridian AI", "meridian-ai", "meridian-ai"),
];

export const WORKDAY_COMPANIES: CatalogCompany[] = [
  workday("Nvidia", "nvidia", "nvidia", "NVIDIAExternalCareerSite", "wd5"),
  workday("Salesforce", "salesforce", "salesforce", "External_Career_Site", "wd12"),
  workday("CrowdStrike", "crowdstrike", "crowdstrike", "crowdstrikecareers", "wd5"),
  workday("Adobe", "adobe", "adobe", "external_experienced", "wd5"),
  workday("Capital One", "capital-one", "capitalone", "Capital_One", "wd12"),
  // Round 2: LinkedIn following list
  workday("GSK", "gsk", "gsk", "GSKCareers", "wd5"),
  workday("Accenture", "accenture", "accenture", "AccentureCareers", "wd103"),
  workday("Fiserv", "fiserv", "fiserv", "EXT", "wd5"),
];

export const MANUAL_COMPANIES: CatalogCompany[] = [
  manual("Applied Intuition", "applied-intuition", "https://www.appliedintuition.com/careers"),
  manual("ServiceNow", "servicenow", "https://careers.servicenow.com/"),
  manual("Uber", "uber", "https://www.uber.com/us/en/careers/"),
  manual("DoorDash", "doordash", "https://careers.doordash.com/"),
  manual("Atlassian", "atlassian", "https://www.atlassian.com/company/careers"),
  manual("Amex", "amex", "https://www.americanexpress.com/en-us/careers/"),
  manual("JP Morgan", "jp-morgan", "https://careers.jpmorgan.com/"),
  manual("Morgan Stanley", "morgan-stanley", "https://www.morganstanley.com/careers"),
  manual("Rippling", "rippling", "https://www.rippling.com/careers"),
  manual("PayPal", "paypal", "https://careers.pypl.com/"),
  manual("TikTok", "tiktok", "https://careers.tiktok.com/"),
  manual("Bilt", "bilt", "https://www.biltrewards.com/careers"),
  manual("Oracle", "oracle", "https://www.oracle.com/careers/"),
  manual("Snap", "snap", "https://careers.snap.com/"),
  manual("Intel", "intel", "https://jobs.intel.com/"),
  manual("Deel", "deel", "https://www.deel.com/careers"),
  manual("Kraken", "kraken", "https://www.kraken.com/careers"),
  manual("Inworld AI", "inworld-ai", "https://inworld.ai/careers"),
  manual("Citadel", "citadel", "https://www.citadel.com/careers/"),
  manual("DRW", "drw", "https://www.drw.com/careers"),
  manual("SIG", "sig", "https://careers.sig.com/"),
  manual("Optiver", "optiver", "https://optiver.com/working-at-optiver/careers/"),
  manual("HRT", "hrt", "https://www.hudsonrivertrading.com/careers/"),
  manual("DE Shaw", "de-shaw", "https://www.deshaw.com/careers"),
  manual("2Sigma", "two-sigma", "https://www.twosigma.com/careers/"),
  manual("XTX Markets", "xtx-markets", "https://www.xtxmarkets.com/careers/"),
  manual("Radix Trading LLC", "radix-trading", "https://www.radixtrading.com/careers"),
  manual("GitHub", "github", "https://github.com/about/careers"),
  manual("X", "x", "https://careers.x.com/"),
  manual("Zillow", "zillow", "https://www.zillow.com/careers/"),
  manual("Yelp", "yelp", "https://www.yelp.careers/"),
  manual("Hugging Face", "hugging-face", "https://huggingface.co/jobs"),
  manual("Renaissance", "renaissance", "https://www.rentec.com/Careers.action"),
  manual("Zynga", "zynga", "https://www.zynga.com/careers/"),
  manual("TextQL", "textql", "https://textql.com/careers"),
  manual("Tesla", "tesla", "https://www.tesla.com/careers"),
  manual("Revolut", "revolut", "https://www.revolut.com/careers/"),
  manual("Visa", "visa", "https://usa.visa.com/careers.html"),
  manual("Intuit", "intuit", "https://www.intuit.com/careers/"),
  // Round 2: LinkedIn following list (no public ATS API found)
  manual("Autosana", "autosana", "https://www.ycombinator.com/companies/autosana/jobs"),
  manual("Config", "config", "https://config.inc/careers"),
  manual("Stitch", "stitch", "https://stitch.money/careers"),
  manual("Balyasny Asset Management", "balyasny", "https://bamfunds.com/careers"),
  manual("Lindy", "lindy", "https://www.lindy.ai/careers"),
  manual("o11", "o11", "https://www.ycombinator.com/companies/o11/jobs"),
  manual("Oddpool", "oddpool", "https://www.ycombinator.com/companies/oddpool/jobs"),
  manual("Human Delta", "human-delta", "https://www.humandelta.ai/careers"),
  manual("HF0", "hf0", "https://www.hf0.com"),
  manual("N47", "n47", "https://www.n47.com"),
  manual("Raindrop", "raindrop", "https://raindrop.ai/careers"),
  manual("Nutanix", "nutanix", "https://careers.nutanix.com"),
  manual("Revyl", "revyl", "https://www.revyl.ai/careers"),
  manual("Ardent", "ardent", "https://www.ycombinator.com/companies/ardent/jobs"),
  manual("Emergent", "emergent", "https://emergent.sh/careers"),
  manual("Resolve AI", "resolve-ai", "https://resolve.ai/careers"),
  manual("Futures First", "futures-first", "https://www.futuresfirst.com/careers"),
  manual("fileAI", "fileai", "https://www.file.ai/careers"),
  manual("Arcana", "arcana", "https://www.arcana.io"),
  manual("Shaped", "shaped", "https://www.shaped.ai/careers"),
  manual("Vizient", "vizient", "https://careers.vizientinc.com"),
  manual("micro1", "micro1", "https://www.micro1.ai/careers"),
  manual("Viasat", "viasat", "https://careers.viasat.com"),
  manual("Qdrant", "qdrant", "https://qdrant.join.com"),
  manual("Eclypsium", "eclypsium", "https://eclypsium.com/company/careers/"),
  manual("NetApp", "netapp", "https://careers.netapp.com"),
  manual("OpenGradient", "opengradient", "https://www.opengradient.ai"),
  manual("Handle", "handle", "https://usehandle.ai/jobs"),
  manual("Hilbert", "hilbert", "https://hilberts.ai/careers"),
  manual("Babylon Labs", "babylon-labs", "https://babylonlabs.io"),
  manual("Treeline", "treeline", "https://www.treeline.ai/careers"),
  manual("Pillar", "pillar", "https://trypillar.com/jobs"),
  manual("GitButler", "gitbutler", "https://gitbutler.com"),
  manual("Preset", "preset", "https://preset.io/careers/"),
  manual("QuiverAI", "quiverai", "https://quiver.ai"),
  manual("Pluvo", "pluvo", "https://pluvo.io/careers"),
  manual("UpSmith", "upsmith", "https://www.upsmith.com"),
  manual("Stoke Space", "stoke-space", "https://www.stokespace.com/careers"),
  manual("Haladir", "haladir", "https://www.ycombinator.com/companies/haladir/jobs"),
  manual("Synchrony", "synchrony", "https://www.synchronycareers.com"),
  manual("Airbase", "airbase", "https://www.airbase.us/careers"),
  manual("You.com", "you-com", "https://you.com"),
  manual("Luma", "luma", "https://lumalabs.ai/join"),
  manual("Hyperliquid", "hyperliquid", "https://hyperliquid.xyz"),
  manual("Driver", "driver", "https://www.driver.ai"),
  manual("Everpure", "everpure", "https://jobs.pentair.com"),
  manual("QuestDB", "questdb", "https://questdb.com/careers/"),
  manual("TradersPost", "traderspost", "https://traderspost.io"),
  manual("Clark Associates", "clark-associates", "https://www.clarkassociatesinc.biz/careers"),
  manual("Timebeat", "timebeat", "https://www.timebeat.app"),
  manual("OfferPilot", "offerpilot", "https://offerpilotai.com"),
  manual("Afterprime", "afterprime", "https://afterprime.com"),
  manual("Palo Alto Networks", "palo-alto-networks", "https://jobs.paloaltonetworks.com"),
  manual("STAC Research", "stac-research", "https://www.stacresearch.com"),
];

export const ALL_CATALOG_COMPANIES: CatalogCompany[] = [
  ...LEGACY_COMPANIES,
  ...GREENHOUSE_COMPANIES,
  ...LEVER_COMPANIES,
  ...ASHBY_COMPANIES,
  ...WORKDAY_COMPANIES,
  ...MANUAL_COMPANIES,
];
