export type PrepDrillChoice = {
  id: string;
  label: string;
};

export type PrepDrillSeed = {
  slug: string;
  topicSlug: string;
  scenario: string;
  choices: PrepDrillChoice[];
  correctChoiceId: string;
  explanation: string;
};

function drill(
  topicSlug: string,
  id: string,
  scenario: string,
  correct: string,
  wrong1: string,
  wrong2: string,
  wrong3: string,
  explanation: string,
): PrepDrillSeed {
  return {
    slug: `${topicSlug}-${id}`,
    topicSlug,
    scenario,
    choices: [
      { id: "a", label: correct },
      { id: "b", label: wrong1 },
      { id: "c", label: wrong2 },
      { id: "d", label: wrong3 },
    ],
    correctChoiceId: "a",
    explanation,
  };
}

export const PREP_DRILLS: PrepDrillSeed[] = [
  // Arrays, Strings & Hashing (5)
  drill(
    "arrays-hashing",
    "complement",
    "Given an integer array and a target, return indices of two numbers that add up to the target. Each input has exactly one solution.",
    "Hash map storing value → index for O(1) complement lookup",
    "Sort array and use two pointers from both ends",
    "Sliding window over contiguous subarray sums",
    "Dynamic programming over prefix sums",
    "You need to find a pair by complement — not a contiguous segment. A hash map gives O(1) 'have I seen target - x?' checks in one pass.",
  ),
  drill(
    "arrays-hashing",
    "group-anagrams",
    "Group strings so that anagrams sit in the same bucket. Order within groups does not matter.",
    "Hash map keyed by sorted string or character frequency tuple",
    "Trie over all prefixes of each word",
    "Union-find to merge connected strings",
    "Binary search after sorting the full list lexicographically",
    "Grouping by a canonical key (sorted chars or frequency signature) is the classic hash-map grouping pattern.",
  ),
  drill(
    "arrays-hashing",
    "top-k-freq",
    "Return the k most frequent elements from an integer array. k is much smaller than unique values.",
    "Counter + size-k min-heap (or Counter.most_common for static arrays)",
    "Full sort of all unique elements by frequency",
    "BFS level-order traversal",
    "Backtracking over all k-sized subsets",
    "Frequency counting plus a bounded heap (or most_common) avoids sorting the entire frequency list.",
  ),
  drill(
    "arrays-hashing",
    "consecutive-seq",
    "Find the length of the longest consecutive integer sequence in an unsorted array in O(n) time.",
    "Hash set — only start a streak from numbers with no predecessor",
    "Sort the array then scan for runs",
    "Sliding window over sorted unique values",
    "DFS on implicit graph of value ± 1",
    "Set membership lets you detect sequence starts (no num-1 present) and extend each streak in O(1) per element amortized.",
  ),
  drill(
    "arrays-hashing",
    "product-except",
    "Return an array where each index holds the product of all elements except itself. No division allowed.",
    "Prefix and suffix products in two passes",
    "Hash map of cumulative products",
    "Heap to repeatedly extract min and max",
    "Recursion with memo on index ranges",
    "Two-pass prefix/suffix accumulation is a one-dimensional scan pattern — not DP state over choices.",
  ),

  // Sorting & Intervals (4)
  drill(
    "sorting-intervals",
    "overlap-check",
    "Given meeting intervals [start, end), determine if one person can attend all meetings.",
    "Sort by start, scan — overlap if start[i] < end[i-1]",
    "Merge all intervals first, then count pieces",
    "Min-heap of end times to count rooms",
    "Dynamic programming over interval ordering",
    "Boolean overlap only needs a linear scan after sorting by start — merging is unnecessary unless output requires merged intervals.",
  ),
  drill(
    "sorting-intervals",
    "merge-intervals",
    "Merge all overlapping intervals and return the non-overlapping cover.",
    "Sort by start, extend current interval or push new one",
    "Union-find on overlapping pairs",
    "BFS from each unvisited interval",
    "Hash map keyed by interval length",
    "Classic sort-and-merge scan: extend end when overlapping, otherwise start a new merged interval.",
  ),
  drill(
    "sorting-intervals",
    "min-rooms",
    "Find the minimum number of conference rooms required so every meeting can happen.",
    "Sort starts, min-heap of end times — reuse room when earliest end ≤ next start",
    "Merge intervals then count resulting segments",
    "Topological sort on meeting dependencies",
    "Two pointers on unsorted interval list",
    "Room reuse is a scheduling problem — min-heap of finish times tracks the earliest freeing room.",
  ),
  drill(
    "sorting-intervals",
    "insert-interval",
    "Insert a new interval into a sorted non-overlapping interval list and merge if needed.",
    "Linear merge pass: append before, merge overlaps, append after",
    "Binary search only — no merge pass",
    "Backtracking over insertion positions",
    "Graph shortest path between interval endpoints",
    "Sorted intervals + one linear merge pass handles insertion and overlap in O(n).",
  ),

  // Sliding Window & Two Pointers (4)
  drill(
    "sliding-window",
    "longest-substring",
    "Find the length of the longest substring without repeating characters.",
    "Variable sliding window with hash map of last seen index",
    "Try every substring and check uniqueness with a set",
    "Sort characters then two pointers on sorted array",
    "DFS exploring all paths through the string",
    "Contiguous substring + validity constraint (no repeats) → shrink/expand window while tracking last positions.",
  ),
  drill(
    "sliding-window",
    "min-window",
    "Find the smallest substring of s that contains all characters of t (including multiplicity).",
    "Variable window — expand until valid, shrink while valid to minimize",
    "Sort both strings and merge",
    "Dijkstra on character graph",
    "DP over (i, j) substring indices with optimal substructure",
    "Need all required chars in a contiguous segment — classic expand-until-valid, shrink-while-valid window.",
  ),
  drill(
    "sliding-window",
    "fixed-anagram",
    "Find all start indices in s where an anagram of p appears as a length-|p| substring.",
    "Fixed-size window of length |p| with character count comparison",
    "Sort every substring of length |p|",
    "Trie insert all rotations of p",
    "Union-find on matching characters",
    "Fixed window size k with frequency counts — slide one char in, one out.",
  ),
  drill(
    "sliding-window",
    "sorted-two-sum",
    "In a sorted array, find two numbers that sum to target. Return their 1-based indices.",
    "Two pointers from left and right ends",
    "Hash map complement lookup",
    "Sliding window over contiguous subarrays",
    "Binary search for each element's complement",
    "Sorted order enables two pointers moving inward based on whether the current sum is too large or small.",
  ),

  // Stacks & Linked Lists (4)
  drill(
    "stacks-lists",
    "valid-parens",
    "Determine if a string of brackets is valid — every opener has a matching closer in correct order.",
    "Stack — push openers, pop on matching closer",
    "Count open and close without ordering",
    "BFS over bracket configurations",
    "DP over substring validity table",
    "Nested LIFO structure → stack. Order of closing must match most recent opener.",
  ),
  drill(
    "stacks-lists",
    "daily-temps",
    "For each day, return how many days until a warmer temperature. If none, return 0.",
    "Monotonic decreasing stack of indices",
    "Min-heap of future temperatures",
    "Sort temperatures with original indices",
    "DFS on implicit temperature graph",
    "Next greater element pattern — monotonic stack compares each day against previous cooler days.",
  ),
  drill(
    "stacks-lists",
    "merge-lists",
    "Merge two sorted linked lists into one sorted list.",
    "Iterative merge with dummy node and two pointers",
    "Push all values into a min-heap",
    "Hash map from value to node",
    "Backtracking over all merge orderings",
    "Two sorted sequences + pointer discipline — dummy head avoids empty-list edge cases.",
  ),
  drill(
    "stacks-lists",
    "lru-cache",
    "Design a structure supporting get(key) and put(key, value) in O(1), evicting least recently used when at capacity.",
    "Hash map + doubly linked list or OrderedDict for recency",
    "Single hash map with timestamp on each access",
    "Trie keyed by access order",
    "Min-heap of (timestamp, key) for eviction only",
    "O(1) lookup needs a dict; O(1) recency update needs a linked order structure — classic composition.",
  ),

  // Binary Search & Bisect (4)
  drill(
    "binary-search",
    "search-insert",
    "Given a sorted array and target, return index if found else insertion position to keep order.",
    "Standard binary search / bisect_left on sorted array",
    "Hash map from value to index",
    "Linear scan — array is small anyway",
    "Sort the array first then scan",
    "Exact position in sorted data is pure binary search — O(log n) on already sorted input.",
  ),
  drill(
    "binary-search",
    "time-map",
    "Design a key-value store where each key holds versioned (timestamp, value) pairs. get(key, t) returns latest value at or before t.",
    "Per-key sorted history + bisect_right on timestamps",
    "Hash map with single latest value only",
    "Trie over timestamp digits",
    "BFS through version graph",
    "Query is 'latest value ≤ t' on sorted timestamps — bisect on append-only history per key.",
  ),
  drill(
    "binary-search",
    "first-last",
    "Find the first and last position of target in a sorted array with duplicates.",
    "Binary search for leftmost and rightmost boundaries",
    "Hash set of all target indices",
    "Sliding window over equal elements",
    "Union-find on adjacent equal values",
    "Two boundary searches (bisect_left / bisect_right style) locate the equal-run edges in O(log n).",
  ),
  drill(
    "binary-search",
    "weighted-jobs",
    "Given jobs with start, end, and profit, pick non-overlapping jobs to maximize total profit.",
    "Sort by end time + binary search for compatible previous job + DP/memo",
    "Greedy: always pick shortest job",
    "BFS over job dependency graph",
    "Trie over job time ranges",
    "Weighted interval scheduling — sort by end, bisect_left finds last compatible job for memoized DP.",
  ),

  // Recursion & Backtracking (4)
  drill(
    "recursion-backtracking",
    "word-search",
    "Given a grid of letters and a word, determine if the word exists by traversing adjacent cells without reusing a cell.",
    "DFS/backtrack from each cell — mark visited, recurse 4 dirs, unmark",
    "BFS shortest path in grid",
    "Dynamic programming on full grid state",
    "Sort letters then binary search",
    "Grid exploration with temporary visited marking and undo is classic backtracking.",
  ),
  drill(
    "recursion-backtracking",
    "combination-sum",
    "Find all unique combinations from candidates where chosen numbers sum to target. Same number may be used repeatedly.",
    "Backtracking from start index — include candidate and stay, or skip forward",
    "Generate all subsets then filter by sum",
    "Dijkstra on sum state graph",
    "Topological sort on candidates",
    "Unordered combinations with reuse → DFS with start index to avoid duplicate combos.",
  ),
  drill(
    "recursion-backtracking",
    "permutations",
    "Return all permutations of distinct integers.",
    "Backtracking with used set — swap or choose at each position",
    "Sort and scan for next lexicographic permutation only",
    "BFS layer by layer building permutations",
    "Hash map frequency count",
    "All orderings of full set → backtracking with used tracking at each depth.",
  ),
  drill(
    "recursion-backtracking",
    "n-queens",
    "Place n queens on an n×n board so no two attack each other. Return all distinct solutions.",
    "Backtracking row by row with column and diagonal conflict sets",
    "Try all n^n placements and filter",
    "Union-find on attacking pairs",
    "Greedy: place queen in first free column per row",
    "Constraint satisfaction with row-by-row choices and conflict tracking is backtracking.",
  ),

  // Trees (4)
  drill(
    "trees",
    "max-depth",
    "Find the maximum depth of a binary tree.",
    "Recursive DFS — 1 + max(left, right) depth",
    "BFS only — DFS cannot compute depth",
    "Sort nodes by value then scan",
    "Union-find on parent pointers",
    "Simple bottom-up aggregation: depth from children determines parent depth.",
  ),
  drill(
    "trees",
    "diameter",
    "Return the length of the longest path between any two nodes in a binary tree (path may pass through root).",
    "Postorder DFS — track best path through each node as left_depth + right_depth",
    "BFS from every node",
    "Sort nodes by height",
    "Trie over root-to-leaf paths",
    "Global optimum from subtree depths at each node — postorder bottom-up aggregation.",
  ),
  drill(
    "trees",
    "validate-bst",
    "Determine if a binary tree is a valid BST.",
    "DFS with min/max bounds passed down (or inorder strict increase check)",
    "Check only immediate parent-child ordering",
    "BFS level order comparison",
    "Hash set of seen values",
    "BST validity is a range constraint propagated top-down (or monotonic inorder traversal).",
  ),
  drill(
    "trees",
    "path-sum",
    "Determine if the tree has a root-to-leaf path whose node values sum to target.",
    "Top-down DFS subtracting current value from remaining target",
    "Postorder aggregate all subtree sums first",
    "Topological sort on tree nodes",
    "Heap of path sums",
    "Path from root carries running sum context down — top-down DFS with target reduction.",
  ),

  // Tries (4)
  drill(
    "tries",
    "implement-trie",
    "Implement a trie supporting insert, search, and startsWith(prefix) for lowercase English words.",
    "Trie — nested dict/map per character with terminal flag",
    "Hash set of all inserted words only",
    "Sorted array + binary search per prefix",
    "Union-find on shared prefixes",
    "Prefix queries are the trie's reason to exist — explicit prefix tree nodes.",
  ),
  drill(
    "tries",
    "add-search-word",
    "Design a structure like a trie but search supports '.' as a wildcard matching any letter.",
    "Trie traversal — on '.' recurse to all children at that level",
    "Hash map with regex compilation per search",
    "Sort all words and binary search",
    "BFS over edit distance graph",
    "Wildcard at a trie node means branching to every child — DFS on trie structure.",
  ),
  drill(
    "tries",
    "word-search-ii",
    "Given a board and a list of words, return all words that can be formed by adjacent cell paths.",
    "Build trie from words + DFS board while walking trie, prune dead branches",
    "For each word run separate Word Search I DFS",
    "Sort words by length then greedy match",
    "DP over (cell, word_index) for all words at once without trie",
    "Trie shares prefixes across words so one board DFS prunes early — combine trie + grid backtracking.",
  ),
  drill(
    "tries",
    "prefix-search",
    "Return all words in a dictionary that start with a given prefix. Many queries expected.",
    "Trie — walk prefix then DFS collect terminal nodes below",
    "Scan entire dictionary each query",
    "Sort dictionary and bisect on prefix",
    "Heap of words by frequency",
    "Repeated prefix queries → trie descent to prefix node then collect subtree words.",
  ),

  // Heaps & Queues (4)
  drill(
    "heaps-queues",
    "kth-largest",
    "Find the kth largest element in an unsorted array.",
    "Size-k min-heap — evict smallest when larger element arrives",
    "Full sort and index k",
    "BFS layers from max element",
    "Trie over bit representations",
    "Streaming top-k → maintain min-heap of size k, not full sort.",
  ),
  drill(
    "heaps-queues",
    "task-scheduler",
    "Given tasks with cooldown n, find minimum intervals to complete all tasks (same task must wait n slots).",
    "Max-heap of remaining counts + queue/cooldown tracking (or math on frequencies)",
    "Sort tasks alphabetically and scan",
    "DFS exploring all valid orderings",
    "Union-find on task pairs",
    "Repeatedly schedule most frequent available task — heap + cooldown queue models 'next best active item.'",
  ),
  drill(
    "heaps-queues",
    "rotting-oranges",
    "In a grid, fresh oranges rot when adjacent to rotten ones each minute. Return minutes until no fresh remain, or -1.",
    "Multi-source BFS with deque — all rotten cells enqueued at time 0",
    "DFS from each rotten orange independently",
    "Dijkstra with rotten as sources",
    "Sort cells by Manhattan distance",
    "Equal-cost simultaneous spread from multiple sources → BFS with deque, not heap.",
  ),
  drill(
    "heaps-queues",
    "find-median",
    "Design a data structure that supports addNum and findMedian in efficient time.",
    "Two heaps — max-heap for lower half, min-heap for upper half",
    "Sorted list with insort on every insert",
    "Single min-heap only",
    "Hash map frequency table",
    "Median maintenance is the classic two-heap partition pattern.",
  ),

  // Graphs & Scheduling (5)
  drill(
    "graphs",
    "course-schedule",
    "There are n courses with prerequisite pairs. Determine if you can finish all courses.",
    "Topological sort — Kahn's algorithm with indegree queue",
    "DFS cycle detection on prerequisite graph",
    "Union-find on course pairs",
    "Dijkstra from course 0",
    "Prerequisite DAG reachability / cycle detection → topological sort (BFS indegree or DFS colors).",
  ),
  drill(
    "graphs",
    "num-islands",
    "Count the number of islands in a 2D grid of '1' land and '0' water.",
    "DFS or BFS flood-fill from each unvisited land cell",
    "Union-find on adjacent land cells",
    "Sort cells and binary search",
    "DP on grid diagonals",
    "Connected components in implicit grid graph → DFS/BFS flood fill (union-find also works).",
  ),
  drill(
    "graphs",
    "cheapest-flights",
    "Find cheapest price from src to dst with at most k stops in a weighted directed graph.",
    "Modified Dijkstra or Bellman-Ford style relaxation with stop count dimension",
    "Plain BFS — all edges weight 1",
    "Topological sort only",
    "Backtracking all paths",
    "Weighted shortest path with edge-count constraint → Dijkstra with (node, stops) state or k+1 round relaxation.",
  ),
  drill(
    "graphs",
    "redundant-connection",
    "In a graph that started as a tree, one extra edge was added. Return the edge that can be removed to restore a tree.",
    "Union-find — first edge connecting already-connected nodes is redundant",
    "DFS from every node",
    "Topological sort",
    "Sort edges by weight",
    "Dynamic connectivity / detecting cycle in undirected graph → union-find.",
  ),
  drill(
    "graphs",
    "word-ladder",
    "Transform beginWord to endWord changing one letter at a time, using only words from wordList. Return shortest transformation length.",
    "BFS on implicit graph of one-letter-apart words",
    "DFS exploring all transformation paths",
    "Dijkstra with random edge weights",
    "Sort wordList and bisect",
    "Unweighted shortest path in implicit graph → BFS, not Dijkstra or DFS.",
  ),

  // Dynamic Programming (5)
  drill(
    "dynamic-programming",
    "house-robber",
    "Rob non-adjacent houses to maximize money. Cannot rob two adjacent houses.",
    "1D DP — at each house: max(rob + skip prev, skip)",
    "BFS over house states",
    "Greedy: rob every other house from the start",
    "Backtracking all subsets",
    "Linear take/skip decision with overlapping subproblems → classic 1D DP.",
  ),
  drill(
    "dynamic-programming",
    "word-break",
    "Determine if string s can be segmented into space-separated dictionary words.",
    "DP — dp(i) = can segment s[i:] by trying dictionary matches from i",
    "BFS over character positions",
    "Trie insert only — no DP needed",
    "Sort dictionary words",
    "Segmentation with reusable substructure → dp(i) boolean on suffix start positions.",
  ),
  drill(
    "dynamic-programming",
    "coin-change",
    "Return fewest coins needed to make amount, or -1 if impossible.",
    "Unbounded knapsack DP — dp[amount] = min over coins",
    "Greedy: always pick largest coin",
    "BFS on amount states",
    "Sort coins and two pointers",
    "Min coins to reach sum with unlimited reuse → bottom-up DP over amounts.",
  ),
  drill(
    "dynamic-programming",
    "decode-ways",
    "Count ways to decode a digit string where '1'-'26' map to letters.",
    "1D DP — dp(i) += valid one-digit and two-digit decodings from i",
    "Backtracking all decode paths only",
    "Trie over digit strings",
    "Graph shortest path",
    "Counting paths with fixed-length transitions from each index → linear DP.",
  ),
  drill(
    "dynamic-programming",
    "not-dp-hint",
    "Find shortest path in an unweighted grid maze from top-left to bottom-right, moving only right or down through open cells.",
    "BFS (or DP since DAG, but BFS is the graph instinct)",
    "Memoized recursion with bitmask over all visited cells",
    "Dijkstra with random weights",
    "Backtracking enumerate all paths",
    "Uniform-cost steps in a grid → BFS. DP works on DAG grids but the tell is unweighted shortest path.",
  ),

  // Design Problems (4)
  drill(
    "design",
    "hit-counter",
    "Count hits in the past 5 minutes. getHits and hit(timestamp) must be efficient.",
    "Deque or queue of timestamps — drop expired from front",
    "Hash map counting hits per second only",
    "Trie over timestamp digits",
    "Full sort on every getHits",
    "FIFO time window → deque of events, evict stale entries from the front.",
  ),
  drill(
    "design",
    "snapshot-array",
    "Support set(index, val) and snap() returning snap_id, then get(index, snap_id) for historical value.",
    "Per-index version history list + bisect on snap_id",
    "Copy entire array on every snap",
    "Single current array only",
    "Graph of snapshot states",
    "Versioned reads per index → append (snap_id, val) when changed; bisect for query.",
  ),
  drill(
    "design",
    "encode-decode",
    "Design encode and decode for a list of strings that may contain any characters.",
    "Length-prefix encoding: 'len#string' repeated",
    "Join with comma delimiter",
    "Base64 each string",
    "Trie over concatenated bytes",
    "Delimiter ambiguity → length-prefix (or escape) encoding, not naive join.",
  ),
  drill(
    "design",
    "browser-history",
    "Implement visit(url), back(), and forward() with a browsing history.",
    "Array/list with current pointer — truncate forward on new visit",
    "Two stacks for back and forward stacks",
    "Hash map url → index",
    "Queue of visited urls",
    "Linear history with pointer — array + index models back/forward truncation.",
  ),

  // Python Toolbox (4)
  drill(
    "python-toolbox",
    "defaultdict-get",
    "You build an adjacency list with graph[u].append(v) but some nodes only appear as destinations. Safest pattern?",
    "defaultdict(list) — d[u].append(v) auto-creates keys",
    "Regular dict with .get(u) then append",
    "Counter for adjacency",
    "OrderedDict only",
    "defaultdict creates missing keys on __getitem__ (d[key]), not on .get() — silent bugs come from mixing patterns.",
  ),
  drill(
    "python-toolbox",
    "max-heap",
    "You need a max-heap of integers in Python's heapq module.",
    "Negate values when pushing — heapq is min-heap only",
    "Use sorted() after every insert",
    "Use list as max-heap natively",
    "Import MaxHeap from heapq",
    "heapq is min-only — negate priorities or store (-priority, item) tuples.",
  ),
  drill(
    "python-toolbox",
    "lru-cache-args",
    "@lru_cache on dfs(nums, path) fails because path is a list. Fix?",
    "Pass hashable state — tuple(path) or separate index parameters",
    "Convert list to string with join",
    "Use global variable for path",
    "Remove memoization entirely always",
    "Memo keys must be hashable — tuple(indices) or positional args, not mutable lists.",
  ),
  drill(
    "python-toolbox",
    "deque-bfs",
    "You need a queue for BFS on a graph with 10k nodes. Best structure?",
    "collections.deque with append/popleft",
    "list with pop(0)",
    "heapq for FIFO order",
    "set for queue storage",
    "list.pop(0) is O(n) — deque gives O(1) ends for BFS.",
  ),

  // Clean Code & Execution (4)
  drill(
    "clean-code-execution",
    "recognize-first",
    "You have 35 minutes for a medium problem. What should happen in the first 2 minutes?",
    "Name the problem family and state the core invariant or state",
    "Start coding the brute force immediately",
    "Memorize the exact LeetCode solution name",
    "Draw the full UML class diagram",
    "Recognition before implementation — family + invariant unlocks the right template.",
  ),
  drill(
    "clean-code-execution",
    "before-code",
    "Interviewer says 'any questions before you code?' What earns trust fastest?",
    "Confirm I/O format, state approach in one sentence, mention one edge case and complexity",
    "Ask if you can use Google",
    "Stay silent and start typing",
    "Ask for the optimal time complexity target only",
    "Structured pre-code checklist: I/O, approach, edge case, complexity — shows calm execution.",
  ),
  drill(
    "clean-code-execution",
    "stuck-mid-code",
    "You lose the thread halfway through implementation. Best recovery move?",
    "Stop typing, restate the invariant aloud, simplify to a helper function",
    "Delete everything and switch algorithms",
    "Ask for the answer",
    "Keep coding hoping it compiles",
    "Calm execution means restating invariant and decomposing — not panic-switching patterns.",
  ),
  drill(
    "clean-code-execution",
    "oa-pattern",
    "Online assessment: 2 problems in 90 minutes, Python allowed, standard library only. Primary skill being tested?",
    "Fast pattern recognition + clean stdlib composition",
    "Proving novel algorithm theorems",
    "Memorizing enterprise design patterns",
    "Writing production-grade error handling for every edge",
    "OAs reward recognizing families and composing heapq/deque/Counter/bisect — not greenfield invention.",
  ),
];
